# General Application Settings
general:
  manufacturer: "mowbot"      # Default manufacturer for VDA5050 topics
  serial_number: "default"    # Default serial if not specified

# MQTT Broker Settings
# Note: In production, these are often overridden by encrypted DB or Env Vars
broker:
  host: "bd1c42d0ad95443bbfee39d5e63806bc.s1.eu.hivemq.cloud"
  port: 8883
  use_tls: true
  user: "mowbot-fleet-01"
  password: "Serene1054"